### ISSUE TITLE
[knx] Backport SmartHome/J enhancements and fixes

### ISSUE THREAD

**Issue by holgerfriedrich** [openhab/openhab-addons#14502]
knx binding was forked to [SmartHome/J](https://github.com/smarthomej), and in the meantime has evolved in both repositories.

This issue summarizes all improvements done in [openHAB KNX Binding at SmartHome/J](https://github.com/smarthomej/addons/tree/4.0.x/bundles/org.smarthomej.binding.knx)
and the status of backporting those enhancements as discussed in #14129.

- [x] smarthomej/addons#13 - thread safety #14509
- [x] smarthomej/addons#46 - (minor null annotations; I did not import changes to ```Firmware.h``` as it is rewritten in #14050) #14509
- [x] smarthomej/addons#60 - (minor null annotations) #14509
- [x] smarthomej/addons#73 - already implemented, backport doc change, comment on 1.009 #14510
- [x] ⛔ smarthomej/addons#74 - backport doc change, backport dpt22 to sting, maybe new test in KNXCoreTypeMapperTest. Note that Calimero supports more subtypes by now. #14511 (obsoleted by following, 107)
- [x] smarthomej/addons#104 - remove unnecessary workaround in knx (already fixed in calimero 2.4), KNXCoreTypeMapper.java:902 #14503 
- [x] smarthomej/addons#107
  - [x] prepare refactoring of KnxCoreTypeMapper #14534; 
  - [x] documentation of dpts, dpt.lst, #14851
- [x] ⛔ smarthomej/addons#125 - no longer necessary, subtype is not converted to int
- [x] smarthomej/addons#114 - KNXChannel #14534
- [x] smarthomej/addons#162 - fix DPT_Control_Dimming, fix updateState call #14504
- [x] smarthomej/addons#203 - warning for incompatible types, #14534
- [x] smarthomej/addons#206 - UoM #14534
- [x] smarthomej/addons#208
  - [x] Refactor KNXCoreTypeMapper, add RGBW and xyY #14534 ⛔ did not port device readout due to #14050,
  - [x] port reading of manufacturer list from external file #15297  
  - [x] use ```ColorUtil``` from openhab/openhab-core#3434
- [x] smarthomej/addons#219 - Fix RGB conversion #14534
- [x] smarthomej/addons#226 - Remove workarounds obsoleted by Calimero 2.5 #14534
- [x] smarthomej/addons#230 - Add parameter for disabling incoming UoM #14534
- [x] ⛔smarthomej/addons#255 - maybe use the limittooptions, otherwise no because already implemented 
- [x] smarthomej/addons#257 - documentation change #14624
- [x] smarthomej/addons#279 - Fix fallback to DecimalType in number conversion #14534
- [x] smarthomej/addons#299 - Fix replies to requests from bus, rewrite of DeviceThingHandler #14534
- [x] smarthomej/addons#330 - Fix for item above #14534
- [x] smarthomej/addons#349 - Fix DPT 251.600 decoding #14534 
- [x] ⛔smarthomej/addons#371 - to be analyzed, problem is not yet in code base, TODO check again after merging other patches above
- [x] ⛔ smarthomej/addons#436 - ok in current code base
- [x] update update.lst file to announce breaking changes, openhab/openhab-distro#1483

**Comment by holgerfriedrich** [comment]
@J-N-K commented on #14511:
> I think the biggest improvement regarding code style and extensibility comes from the removal of the core type mapper and the refactoring to value(de)coders.

Yes, smarthomej/addons#208 will be fun to merge ;-) It somehow obsoletes the changes done in the meantime.... Will see how it fits together.

The second point I am concerned of is the UOM handling, especially as I have not much experience with it and see a huge potential to break existing installation.....

**Comment by holgerfriedrich** [comment]
Status above still valid, did not find time to complete

**Comment by lolodomo** [comment]
@holgerfriedrich and @J-N-K : can this issue be closed now?

**Comment by holgerfriedrich** [comment]
@lolodomo Status above is valid, new list of manufacturers not backported yet
