### ISSUE TITLE
Checking if upgrade instructions were provided for all OH 4 PRs

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#14928]
As a mechanism was introduced in OH 4 to provide an automatic upgrade of managed things, I think it would make sense that this mechanism was used in all PRs merged in OH4. At the time I am writing this message, we have 515 PRs merged tagged with milestone 4.0.
I think we could at least do a quick control in all these PRs, that is check if a thing was updated in XML files and no upgrade instructions were provided.
I will then list the found PRs here.
Is there someone to help me doing these checks ? I plan to start from the oldest. So if someone would like to start from the most recent, this would help.

Of course, after these PRs are identified, this will require to add upgrade instructions.

- [ ] #13885 : item type was updated (dimension added) for 2 channel types and tags added
- [x] #14030 : channel manual_fan_speed removed => upgrade instructions in #14473
- [ ] #14039 : item type was updated (dimension changed) for channel rain-rate
- [x] #14076 : channels batterystatusupdated and locked added => upgrade instructions in #14572
- [x] #14527 : channel pause added => upgrade instructions in #14572
- [x] #14086 : category and tag added
- [ ] #14155 : channel rawSpeed added
- [ ] #14160 : tags added
- [ ] #14201 : a lot of channels added
- [ ] #14219 : channel state updated (min value)
- [ ] #14236 : channel today_prices added
- [ ] #14277 : channel live_accumulatedReward added
- [ ] #14244 : channels added and channels updated with a new channel type
- [ ] #14245 ? a channel type was added but not added to a thing type, maybe a dynamic channel
- [ ] #14283 : channels name and hostname added
- [ ] #14284 : channels guestVoucher and guestVouchersGenerate added
- [ ] #14319 : channel type rssi updated
- [ ] #14352 : channel type setpoint-temperature updated (read-only)
- [ ] #14400 : channel type updated (state)
- [ ] #14180 : a lot of channels added
- [x] #14447 : 4 channels added => upgrade instructions in #14460
- [ ] #14543 : channel group renamed
- [ ] #14587 : instructions to update a channel "voltage" which does not exist + ref to system channel using ":" to be confirmed
- [ ] #14596 : new channel groups (for dynamic things ?)
- [ ] #14636 : channel valve removed (new channel type on)
- [ ] #14638 : many channels added/removed
- [ ] #14720 : new group "general". Are instructions correct ?
- [ ] #14781 : channel silent-mode added
- [ ] #14896 : item type fixed in channel type humidity

Checked from PR 14896 (page 2)
To be checked: #14622 #14641

**Comment by J-N-K** [comment]
No, but you can workaround that by using "update" instead of "add". Calling "add" when a channel already exists results in an exception, "remove" or "update" don't fail if the channel is not present.

**Comment by jlaur** [comment]
@lolodomo:
- **danfossairunit:** Instructions were added in #14473
- **miele:** Most of the channels can't be fixed without losing the localized channel label and description. I would prefer to not to mess with it, since it's just default tags and two categories.
- **renault:** Instructions were added in #14572

**Comment by florian-h05** [comment]
@lolodomo 

- **evcc**: Binding is using dynamic channels.

**Comment by lsiepel** [comment]
Willing to spare some time, but is this still relevant since 4.0 has allready come out?

**Comment by lolodomo** [comment]
No, unfortunately, it is too late I believe.
