### ISSUE TITLE
Activating cache for TTS services

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#15110]
A LRU cache is available in core framework. The use of this cache has to be enabled for each TTS service:
An option exists to disable the cache..

- [x] Google TTS : PR #15208 
- [x] macOS  TTS : PR #15109 
- [x] Mary TTS: PR #15227 
- [x] Mimic TTS : PR #14564 
- [x] Pico TTS : PR #14565 
- [x] Polly TTS : PR #15228 
- [x] VoiceRSS TTS: PR #14561

**Comment by lolodomo** [comment]
For Polly TTS, do we remove the existing cache or do we let the user choose what cache system to be used (through a new option) ?

**Comment by lolodomo** [comment]
Same question for Google TTS.

**Comment by lolodomo** [comment]
Regarding Mimic and VoiceRSS TTS, it is better to wait for the enhancement of all audio sinks before merging the related PRs.

**Comment by dalgwen** [comment]
> Same question for Google TTS.

As you saw, I forgot your question and directly provided a Google TTS PR...

I have no doubt that the common cache has more functionnality than the custom google one.
(I didn't look at Polly TTS recently but I think it is nearly the same). I think we should make the shift, **on the paper at least**.

My last concern is : is there some remaining unseen bug in the common TTS cache ? No one is complaining in the 4.0. milestone versions, but as it is not implemented in any TTS, the opposite would be surprising !

**Comment by lolodomo** [comment]
> I have no doubt that the common cache has more functionnality than the custom google one. (I didn't look at Polly TTS recently but I think it is nearly the same). I think we should make the shift, **on the paper at least**.

In case you have time to propose the PR before the 16th of July, I will take the time to review and merge it.

> My last concern is : is there some remaining unseen bug in the common TTS cache ? No one is complaining in the 4.0. milestone versions, but as it is not implemented in any TTS, the opposite would be surprising !

I made tests myself with positive results. I am running the VoiceRSS updated version since several days.

**Comment by lolodomo** [comment]
Now done for all TTS services
