### ISSUE TITLE
Thing actions should have a unique id

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#17707]
Bindings sometimes define several thing actions with the same method name leading to thing actions having the same id. It should be fixed. openhab/openhab-core#4438 allows defining action id not depending on method name and as a consequence allows avoidding  thing actions with the same id when the same method name is used.

Bindings to be fixed:

- [ ] chromecast (playURL) => PR #17708 
- [ ] ecobee (setHold) => PR #17709 
- [ ] energidataservice => PR #17679 
- [ ] enigma2 => PR #17710 
- [ ] lgwebos => PR #17712 
- [ ] mpd (sendCommand) => PR #17711 
- [ ] mqtt (publishMQTT)
- [ ] ...

All bindings from a until m were checked

**Comment by lolodomo** [comment]
I realise that the id, when it is not the method name, should be mentioned in the documentation as this id is required to run the REST API (run the action).

**Comment by Laith-Budairi** [comment]
is there still a need to do the mqtt binding too?

**Comment by lsiepel** [comment]
> is there still a need to do the mqtt binding too?

There is another PR in core that generates these id’s automatically. So this makes the live of contributors and maintainers a little easier as we do not need to care about the id in the bindings.

**Comment by lolodomo** [comment]
The need disappeared with the enhancement in progress in core framework.
But the discussion in the core PR revealed another issue that should be fixed in bindings: you must not define several classes with the same action scope. I know for example caddx or freeboxos doing that.
@J-N-K explained this constraint.

**Comment by lolodomo** [comment]
I am know closing th me issue as the core PR fixing the problem has been merged.
