### ISSUE TITLE
[miio] Binding enhancements

### ISSUE THREAD

**Issue by marcelrv** [openhab/openhab-addons#7276]
Placeholder / braindump for next set of features planned / wished for in the miio binding

# Cloud
- [x] Allow to send commands to devices via the cloud besides direct (#8981)
Add option to binding and device config to select the communication patther
Options 0 direct than try cloud, 1 direct, 2 cloud
Note this also possibly allows to receive info not received directly from device e.g. powerusage for plugs, info from Bluetooth devices etc
- [ ] Cloud events subscription
Allow support for devices like Xiaomi Mijia AI Video Doorbell, or various lumi devices like motion sensors, button as these don't have a property to query but only create events
- [X] Support to pull some parameters from the cloud using custom cloud refresh commands #11715 

# Discovery
- [X] Add method to discover devices from cloud #9176
- [X] Avoid upnp discovery from duplicating devices in discovery #10951
- [x] upnp discovery get token from cloud #8463

# Vacuum
- [x] Add support for dynamic channels for newer devices
- [x] Crop the map in case blue borders are too large #11110
- [X] Configurable scaling of the map #11110

# Basic handler
- [X] Add map of variables  e.g. $smooth$ to allow for multi parameter commands to be send
add channels (if requested) for these variables
have global vars to substitute values-> $did$ #10984
- [x] add parameter defining the QuantityType  type e.g. for Celcius  update with new QuantityType<>(environment.temperature, SIUnits.CELSIUS)); #8756
- [X] dynamically generate channels #9158

## Database improvements
- [ ] Per device add name (+ maybe maturity). Note: adding the name to be able to remove all basic devices from the MiIoDevices.java and drive them directly from the db
- [x] Move from precommand  & post to jsonarray of commands to allow for arbitrary amount of parameters
- [x] Add possibility of refresh command per parameter, so not only the get_properties are done in refresh but others could be as well (allows to support viomi vacuum type devices in basic handler)  #8796
- [X] Support  to add the option values #9158
- [ ] Write documentation for the json database format

# MIOT support
- [x] Create new handler or enhance basic handler to process commands for miot devices
- [X] (in unsupported handler) allow to create database files based on the online miot spec #11149

# Unsupported handler
- [x] Create readable logging to file to allow to easy share device info  #8716
- [x] Test all known commands to see if the device supports them #8716
Start with profile(s) that matches to the device
- [x] Based on testing result automatically create a json database file to run it afterwards as basic device #8716

# Gateways support
- [X] Support newer deviceIds the gateway subdevices are using #10951
- [X] Support substitutions for deviceId and timestamp #10984
- [X] Allow more parameters to be added beside the method (needed for sending commands to subdevices) #11688
- [X] create a bridge handler for gateways, child devices for gateway sub devices #11688

**Comment by micha-tum** [comment]
One more thing that might be useful: For Yeelight lamps, it is currently not possible to turn the lamp on through the RGB channel (RGB brightness > 0 should turn on the lamp, ==0 -> off). Also brightness channel changes of the item are not synced to the RGB channel brightness, only vice versa is synced. Both things are necessary to have it properly working with Google assistant, current workaround is through a dummy item and some rules, but it would be nice to have this directly in the binding. Hope this comment is in the right place here, otherwise just delete it. Thanks for your effort on the binding!

**Comment by mrumpf** [comment]
Allow the binding to be configured via a cfg file: https://community.openhab.org/t/xiaomi-mi-binding-config-file/115287/2

**Comment by marcelrv** [comment]
@mrumpf I believe that is already possible with all binding configurations
You can define the binding configuration through `userdata/config/binding/miio.config`

content: 

:org.apache.felix.configadmin.revision:=L"9"
cloudDiscoveryMode="all"
password="superduperSecret"
service.pid="binding.miio"
username="your@email.com"

**Comment by marcelrv** [comment]
Closing the issue. Remaining on the Wishlist is Cloud events subscription. 
_Allow support for devices like Xiaomi Mijia AI Video Doorbell, or various lumi devices like motion sensors, button as these don't have a property to query but only create events_

However, as this cloudsevents functionality involves a rather complex flow don't expect to implement this.
