### ISSUE TITLE
Proper closing of WebSockets to avoid memory leak / crash

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#8027]
It was recently discovered 2 bindings not correctly closing WebSockets. This leads to memory leak and even openHAB crash.
I think it would be good to check that all bindings using WebSockets are correctly closing WebSockets.

I found 12 bindings using WebSockets:

- [x] amazonechocontrol (PR #7919, PR #8074)
- [x] bosesoundtouch (PR #8031, PR #8073)
- [x] deconz (uses `get()` on connect)
- [x] innogysmarthome (PR #8080)
- [x] kodi (PR #8030)
- [x] lgwebos (PR #8038)
- [x] loxone (PR #8032 closed, PR #8154 closed)
- [x] samsungtv (PR #8025, PR #8072)
- [x] sonyaudio (uses `get()` on connect)
- [x] tibber (PR #8033, PR #8071)
- [x] valloxmv (PR #8035)
- [x] vektiva (uses `get()` on connect)

**Comment by lolodomo** [comment]
I don't find any handling of sessionFuture in the LGwebOS binding for example.

**Comment by Hilbrand** [comment]
What does it mean to correctly close the socket? Can you give a pattern or is it just to make sure `close((` is called always?

**Comment by lolodomo** [comment]
Look at the 2 fixes provided by @J-N-K 

First, in case you are not using the shared WebSocketClient, you are starting and stopping your client. In this case, stop it only if started.
Second, when connecting the WebSocket, the connect method is returning a Future. When closing, check that this future is done and if not cancel it.

@J-N-K : please correct me if I am wrong.

**Comment by J-N-K** [comment]
Yes, the problem is that if the connect did not succeed, the future never completes and stays in memory forever.

**Comment by lolodomo** [comment]
I imagine the future is done after a timeout? 
The LGwebOS is trying to connect every 10 seconds. I should encounter this problem. Maybe I am not because the timeout us lower than 10s ? 
By the way, it would be proper to cancel this future if needed before trying a new connect. This is not something you added in your fix. 
WDYT?

**Comment by lolodomo** [comment]
The problem would occur if you retry connection more often than the connect timeout without cancelling this session future?

**Comment by J-N-K** [comment]
Well, if the future is still there when you try a reconnect, your connection logic is flawed, because you did not close the connection befor opening a new one. Not sure about the timeout, but could be. I didn't look in the code of LGwebOS.

**Comment by J-N-K** [comment]
deconz is not suffering from this issue as it `.get()`s the future immediately. If the connect fails, the `.get()` throws an exception.

**Comment by lolodomo** [comment]
I will check and fix the LGwebOS.

**Comment by J-N-K** [comment]
I left lgwebos to you. You could suffer from the issue if the client connect fails before the connect is finished. After the session is connected, there is no problem anymore.

**Comment by sprehn** [comment]
> First, in case you are not using the shared WebSocketClient client, you are starting and stopping your client. In this case, stop it only if started.

I don't see any flaw in stopping the client in deactivate method without keeping track if it was started or not previously. The client itself will hold this state. If it is already stopped it will ignore the command.

**Comment by sprehn** [comment]
> Yes, the problem is that if the connect did not succeed, the future never completes and stays in memory forever.

There is a connection timeout which defaults to 15s in jetty. For the client in lgwebos it is set to 1s. 
When the timeout occurs the method annotated with @OnWebSocketError will be called.  

The Future should complete in any case.

**Comment by J-N-K** [comment]
In amazonechocontrol it clearly did not work that way and led to an OOM after some time.

**Comment by lolodomo** [comment]
As I mentioned earlier, I believe there is a risk in case the connection retry will occur more frequently than the connect timeout. 
For the LGwebOS binding, if the connect timeout is set to 1s, there is no risk. 
By the way, handling the connection future cannot be a wrong thing.

**Comment by bjoernbrings** [comment]
During the development of my binding (some time ago) I was asking myself whether polling something quite regular isn't a common usecase that could be implemented centrally and then be used by all bindings.

**Comment by lolodomo** [comment]
@J-N-K in the PR for LGwebOS binding @sprehn is challenging one of the two main changes introduced in your PRs. Can you both please continue the discussion so that we are sure that the change applied to all these bindings is really relevant.

**Comment by J-N-K** [comment]
@sprehn then please explain why that change obviously fixes the problem.

**Comment by lolodomo** [comment]
It is still possible that one if your change really fixed one issue but not the second. 
The discussion is about the need or not to check isStarted() before calling stop().

**Comment by sprehn** [comment]
Yes, why protect the call to stop() with isStarted(). stop() implementation handles the internal state and is a no-op if not necessary. But there are two states: STARTED and STARTING. isStarted is only true for STARTED state. So if the state is STARTING when the binding is deactivated stop() would not be called

**Comment by J-N-K** [comment]
Feel free to revert it. Pretty sure you know how to do PR.

**Comment by lolodomo** [comment]
I can help.

**Comment by lolodomo** [comment]
Done.

**Comment by lolodomo** [comment]
One last thing, I see most of the bindings using their own websocket client are calling stop() and destroy() but not all are calling destroy(). LGwebOS and SamsungTV bindings are not for example. Is it important to call destroy too ?

**Comment by lolodomo** [comment]
The innogysmarthome binding is finally to be fixed because it does not stop the WebSocket client it creates and starts.

**Comment by lolodomo** [comment]
@kaikreuzer : as you already merged most of them, can you please also merge #8038 and #8071 before releasing 2.5.7 ?

**Comment by kaikreuzer** [comment]
done.

**Comment by lolodomo** [comment]
I think we can close this issue. All concerned bindings were updated. Just remains a possible doubt about the loxone binding.
