### ISSUE TITLE
Fix disabled integration tests

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#8537]
The following integration tests are still disabled and need to be fixed now that all add-ons have been ported to OH3:

* [x] org.openhab.binding.avmfritz.tests (fixed in #8567)
* [x] org.openhab.binding.feed.tests (caused by https://github.com/openhab/openhab-core/issues/1596, fixed in #8564)
* [x] org.openhab.binding.mqtt.homeassistant.tests (disabled since bnd migration, fixed in #8609)
* [x] org.openhab.binding.mqtt.homie.tests (disabled since bnd migration, fixed in #8609)
* [x] org.openhab.binding.ntp.tests (caused by https://github.com/openhab/openhab-core/issues/1596 and #7834, fixed in #8565)
* [x] org.openhab.io.hueemulation.tests (the add-on itself also needs to be fixed, see #7647, the itest seems to have been removed when the add-ons were ported to OH3)
* [x] org.openhab.io.mqttembeddedbroker.tests (disabled since bnd migration, fixed in #8609)

**Comment by wborn** [comment]
The feed integration tests fails because the [ItemChannelLink](https://github.com/openhab/openhab-addons/blob/main/itests/org.openhab.binding.feed.tests/src/main/java/org/openhab/binding/feed/test/FeedHandlerTest.java#L261-L264)s don't properly work (https://github.com/openhab/openhab-core/issues/1596) and would also be fixed by https://github.com/openhab/openhab-core/pull/1634.
